name: sailbrowser_flutter
description: Sailing results management.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  audioplayers: ^5.1.0
  clock: ^1.1.1
  cloud_firestore: ^4.8.0
  cupertino_icons: ^1.0.2
  data_table_2: ^2.5.8
  firebase_app_check: ^0.2.1+1
  firebase_auth: ^4.6.3
  firebase_core: ^2.13.1
  firebase_ui_auth: ^1.5.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0
  flutter_riverpod: ^2.0.0
  flutter_typeahead: ^4.8.0
  form_builder_extra_fields: ^10.0.0
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.2.0
  go_router: ^12.0.0
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  meta: ^1.9.1
  riverpod_annotation: ^2.1.1
  rxdart: ^0.27.7
  stack_trace: ^1.11.0
  uuid: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  mockito: ^5.4.2
  riverpod_generator:
  test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/images/
